### ISSUE TITLE
Docker image doesnt build anymore 

### ISSUE THREAD

**Issue by Ademord** [NVlabs/Deep_Object_Pose#124]
Hello
I have tried to use your docker image and setup tools does not work with python2 anymore, as per the error when trying to build (Step 2. in the [readme](https://github.com/NVlabs/Deep_Object_Pose/blob/master/docker/readme.md))

**Comment by robonrrd** [comment]
Thank you for letting us know about this.  The cause of the failure you're seeing is a change in the Python setuptools module; we now have to specify a particular version (44.1.1) rather than using the latest. We will check in a fix shortly, but if you want to address it immediately change the line in the Dockerfile that says  `&& pip install setuptools wheel \` to `&& pip install setuptools==44.1.1 wheel \` and re-run the docker build command.
