### ISSUE TITLE
 Pose detection for multi-object scenes

### ISSUE THREAD

**Issue by Suhail99** [NVlabs/Deep_Object_Pose#182]
Hello , its observed in your paper that multiple objects were detected in a single scene. I am keen to know whether the pose estimation done on all YCB objects (at once) which are located in mixed scenes was done using one model or different/seperate models for each object pose estimation? I mean was the model trained for all objects at ones or were the weights generated separately?
Sorry I'm new to this topic! Thanks in Advance.

**Comment by TontonTremblay** [comment]
Each object has its own set of weights. You can run them in parallel on a machine no problems. When this project was developed it was quite hard to get high accuracy of a single model trained on multiple objects. The state of the art has change since with things like cozy pose (which relies on an online renderer to fine tune the pose). I would suggest you to look at the 6D challenge and see the new techniques being developed for pose estimation. In our experiments, I find that using a simple approach like DOPE here to be quite interesting for accessibility purposes. e.g., using an online renderer can be challenging.
