### ISSUE TITLE
Problems about creating domain randomized images by NDDS?!

### ISSUE THREAD

**Issue by chibai** [NVlabs/Deep_Object_Pose#40]
In your paper, ' solid colored background, photograph (from a subset of 10,000 images from the COCO dataset [21]), or procedurally generated background image with random multicolored grid pattern'
I have 2 questions, please give a hint if possible.
Because I'm totally new in render area, so I may use some **unprofessional words**.

question 1: what kind of scene capture did you use? SceneCapturer_Simple? SceneCapturer_Zed?SceneCapturer_IntelRealSense SR300?SR300_Color_Cam_BP or SR300_InfraredCam_BP??

question 2: how to set the backgrounds of the image. As far as I knew, image has to be related to objects. Right now, I'm creating a Plane, and set the image to the surface of the plane, then I put the capture in front of the plane? Is this the right way to create the backgournd the the domain randomrized images??

**Comment by TontonTremblay** [comment]
We did not release any content with the NDDS tool, but we did release the tool used for doing it. In order to reproduce the dataset you will have to create the UE4 scenes yourself.

If you look into NDDS documentation you should see how to randomize textures using imported images in a folder. I think SceneCapturer_Simple is set for randomizing the background of the scene using generated texture.
