### ISSUE TITLE
Do you have change the size of obj?

### ISSUE THREAD

**Issue by qingchenkanlu** [NVlabs/Deep_Object_Pose#78]
I open the YCB obj in 3ds max and I get the size of model is smaller than the real size ,do you have change the size of .obj before make dataset?

**Comment by thangt** [comment]
We didn't change the size of the .obj. How much did you detect the size changed?

**Comment by qingchenkanlu** [comment]
I get the model size of master chef in 3ds max is x=0.27cm y=0.286cm z=0.376cm, is it correct?

**Comment by mintar** [comment]
The master chef can has the following dimensions in the original YCB model (in **meters**):

x = 0.1025
y = 0.1024
z = 0.1402

The aligned model used by DOPE (see [NVDU](https://github.com/NVIDIA/Dataset_Utilities#nvdu_ycb)) has the following dimensions (in **centimeters**):

x = 10.24
y = 14.01
z = 10.23

**Comment by qingchenkanlu** [comment]
Thank you! @mintar Is x = 10.24 y = 14.01 z = 10.23 is equal to the actual object size?

**Comment by qingchenkanlu** [comment]
Sorry, I want to ask you one more question @mintar ,you said [https://github.com/NVlabs/Deep_Object_Pose/issues/5#issuecomment-494708568](url),I use the meshroom to make object model,but the result is awful
![2](https://user-images.githubusercontent.com/44363924/65669884-e688d280-e076-11e9-8749-134c9f9a1a96.png)
![3](https://user-images.githubusercontent.com/44363924/65669903-ee487700-e076-11e9-8484-298e26800989.png)
I want to know how to make a good model like YCB object model?

**Comment by mintar** [comment]
> Thank you! @mintar Is x = 10.24 y = 14.01 z = 10.23 is equal to the actual object size?

Yes.

> Sorry, I want to ask you one more question @mintar ,you said #5 (comment) use the meshroom to make object model,but the result is awful

You have to post-process the mesh that meshroom produces. At least, open the mesh in a mesh editing tool (like Blender or Meshlab) and cut out the table plane. Also, rescale it to fit the actual object size (in centimeters) - Meshroom doesn't know the actual size. You will probably get a hole in the mesh where the object was sitting on the table - you'll have to fill that hole, for example by recording a second mesh with Meshroom (with the object turned upside down), and then manually cutting out parts of the two meshes and gluing them together using Blender. Finally, rotate the mesh so that it's aligned with the coordinate system axes and translate it so that the origin is in the bounding box center. It's a lot of manual work unfortunately.

**Comment by mintar** [comment]
Of course you can also use 3D Studio Max instead of Blender / Meshlab.

**Comment by qingchenkanlu** [comment]
@mintar Thank you for your help!
